// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bcxvexnrtmfmgaqynhmw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjeHZleG5ydG1mbWdhcXluaG13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODUwMzAsImV4cCI6MjA3MTM2MTAzMH0.RmLRdWnmcUTea9-SYNQ9VG6ojk1Q2slbg8uVgGiGLHk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});